### ISSUE TITLE
Apelon DTS 3.5 Not found

### ISSUE THREAD

**Issue by kjmpsm0826** [wanghaisheng/old-clinical-decision-support#1]
I'm trying to build openCDS in your source code.
But I can not check out 'Apelon DTS 3.5' from 'https://apelon-dts.svn.sourceforge.net/svnroot/apelon-dts'.
Would you like to tell me how I can build or 'SKIP!!!' it?

**Comment by wanghaisheng** [comment]
that is way too old 。
pls take a look at fhir cdss
